podman_user: "your_local_account_with_passwordless_sudo"
registry_username: "your_oracle_username"
registry_password: "your_oracle_password"
oracle_pwd: "4LSdWeQuGWFssjgkR"
db_conn_string: "sys/4LSdWeQuGWFssjgkR@{{ ansible_default_ipv4.address }}:1521/ORCLCDB"
weblogic_admin_user: "webadmin"
containers_base_dir: "/home/{{ podman_user }}/containers"
oracle_database_image: "container-registry.oracle.com/database/enterprise:21.3.0.0"
ords_image: "container-registry.oracle.com/database/ords:latest"
weblogic_image: "container-registry.oracle.com/middleware/weblogic:14.1.1.0-11"
